In [3]:
import sys
sys.path.append('../')


import pandas as pd
import numpy as np

In [4]:
data1 = pd.read_csv("/home/sonn/Sonn/Workspace/Projects/Anti-Obesity_GBC_NetworkPharmacology/data/raw/GeneCards_Obesity.csv")

In [5]:
data2 = pd.read_csv("/home/sonn/Sonn/Workspace/Projects/Anti-Obesity_GBC_NetworkPharmacology/data/raw/DISGENET_Obesity.csv")

In [6]:
data1.head(3)

,Gene Symbol,Description,Category,Uniprot ID,Gifts,GC Id,Relevance score,GeneCards Link
0,LEP,Leptin,Protein Coding,P41159,59,GC07P128241,78.486198,https://www.genecards.org/cgi-bin/carddisp.pl?...
1,MC4R,Melanocortin 4 Receptor,Protein Coding,P32245,58,GC18M060371,70.720993,https://www.genecards.org/cgi-bin/carddisp.pl?...
2,POMC,Proopiomelanocortin,Protein Coding,P01189,61,GC02M025160,57.869663,https://www.genecards.org/cgi-bin/carddisp.pl?...

In [7]:
data2.head(3)

,Unnamed: 0,numCTs,unitProt,numVariantsGDA,HPOClass,type,evidenceIndexGDA,numDiseasesAssociatedToGene,geneNcbiID,numPMIDs,...,geneDPI,pathwayIDs,numVariantsDisease,proteinClass,DOClass,diseaseClass,semanticType,numGenesDisease,firstRef,scoreGDA
0,NaN,8,P32245,73,Growth abnormality (01507),disease,0.891803,16,4160,96,...,0.87,"R-HSA-1266738,R-HSA-162582",345,G-protein coupled receptor,disease of metabolism (0014667),"Nutritional and Metabolic Diseases,Pathologica...",Disease or Syndrome (T047),300,1957.0,1.0
1,NaN,3,"P13945,A8KAG8",3,Growth abnormality (01507),disease,0.798283,23,155,16,...,0.83,R-HSA-162582,345,G-protein coupled receptor,disease of metabolism (0014667),"Nutritional and Metabolic Diseases,Pathologica...",Disease or Syndrome (T047),300,1995.0,1.0
2,NaN,168,"P41159,A4D0Y8",0,Growth abnormality (01507),disease,0.888000,59,3952,15,...,0.96,"R-HSA-1266738,R-HSA-162582,R-HSA-392499",345,NaN,disease of metabolism (0014667),"Nutritional and Metabolic Diseases,Pathologica...",Disease or Syndrome (T047),300,1997.0,1.0

In [8]:
data1_new = data1['Gene Symbol']

In [9]:
data2_new = data2['gene']

In [10]:
data1_new_list = np.array(data1_new).tolist()

In [11]:
data2_new_list = np.array(data2_new).tolist()

In [12]:
for i in data2_new_list:
    if i not in data1_new_list:
        data1_new_list.append(i)

In [13]:
len(data1_new_list)

11397

In [14]:
data_final = pd.DataFrame(data1_new_list)

In [15]:
data_final.columns = ['Gene']

In [16]:
data_final

          Gene
0          LEP
1         MC4R
2         POMC
3         LEPR
4          FTO
...        ...
11392   ZBTB7B
11393   PEX11A
11394     ZFR2
11395      ND1
11396  ALDH1L1

[11397 rows x 1 columns]

In [18]:
data_final.drop_duplicates()

          Gene
0          LEP
1         MC4R
2         POMC
3         LEPR
4          FTO
...        ...
11392   ZBTB7B
11393   PEX11A
11394     ZFR2
11395      ND1
11396  ALDH1L1

[11397 rows x 1 columns]

In [19]:
data_final.to_csv("../data/final/ObesityGenes.csv", index=False)